### ISSUE TITLE
Parse Cwl's "Any" type

### ISSUE THREAD

**Issue by danbills** [broadinstitute/wdl4s#145] opened 2017-07-19 12:40 UTC
CWL specifies an [Any](http://www.commonwl.org/v1.0/Workflow.html#Any) type that "validates for any non-null value."

As of this writing there is a placeholder type called `CwlAny` in TypeAliases.

**Comment by katevoss** [comment] 2017-10-11 17:15
Dupe of #122

**Closed by katevoss** 2017-10-11 17:15 UTC
